version: "3"

services:

    signaling-server:
        build:
            context: signaling-server
#        command: ["tail", "-f", "/dev/null"]
        command: [ "sh", "/run-signaling-server.sh" ]
        # command: "/run-signaling-server.sh"


    reverse-proxy:
        ports:
          - 443:443
        build:
            context: reverse-proxy
