version: "3"

services:

    signaling-server:
        ports:
        - 8080:8080
        build:
            context: signaling-server
        command: /run-signaling-server.sh


    static-file-server:
        ports:
        - 1984:80
        build:
            context: static-file-server
