FROM node:lts-alpine3.9
#RUN echo install socket
#RUN npm install socket.io
#RUN echo install express
#RUN npm install express
#RUN echo copy sh
#COPY ./run-signaling-server.sh /run-signaling-server.sh
#RUN echo copy js
#COPY ./signaling-server.js /signaling-server.js
#RUN echo set entrypoint
#ENTRYPOINT [ "sh", "/run-signaling-server.sh" ]